web:
  api_host: 0.0.0.0:6000
  debug_host: 0.0.0.0:7000
  read_timeout: 5
  write_timeout: 5
  shutdown_timeout: 5
zipkin:
  local_endpoint: 0.0.0.0:9411
  reporter_uri: http://zipkin:9411/api/v2/spans
  service_name: reader
  probability: 0.05
database:
  user: postgres
  password: postgres
  host: 0.0.0.0
  name: nimbler
  disable_tls: true
